### ISSUE TITLE
Missing declaration files.

### ISSUE THREAD

**Issue by colinherzog-fhnw** [dappsnation/ng-rive#15]
When installing and importing Rive as a Module in a Module, following error appears:

node_modules/ng-rive/lib/component/node.d.ts:4:22 - error TS7016: Could not find a declaration file for module 'rive-canvas'. '/xxxxx/node_modules/rive-canvas/rive.min.js' implicitly has an 'any' type.
  Try `npm install @types/rive-canvas` if it exists or add a new declaration (.d.ts) file containing `declare module 'rive-canvas';`

Installting those types, including new declaration files, or ts-ignoring don't do anything.

**Comment by GrandSchtroumpf** [comment]
Try running `npm i rive-canvas@0.6.10`. The definition files are in this package. I'm currently not supporting latest version of rive. I'll work on that this weekend

**Comment by GrandSchtroumpf** [comment]
Hello @colinherzog-fhnw,
I've updated to the latest version of angular & rive-canvas. Could you give it a try and let me know how it goes ? 
```typescript
npm install ng-rive@latest
```

**Comment by colinherzog-fhnw** [comment]
Thanks for the update. Seems to be working!
