### ISSUE TITLE
State machine binding error

### ISSUE THREAD

**Issue by n84ck** [dappsnation/ng-rive#20]
Hello! I tried to use state machine in my code but I get bindingError: 'function StateMachineInstance.advance called with 1 arguments, expected 2 args!' when the play is true.

Could you help me why?

`  <canvas riv="rocketWithText">
    <riv-state-machine name="State Machine 1" play>
      <riv-input name="Text" [value]="100"></riv-input>
      <riv-input name="Fire" [value]="100"></riv-input>
      <riv-input name="Move" [value]="100"></riv-input>
    </riv-state-machine>
  </canvas>`

**Comment by GrandSchtroumpf** [comment]
Which version of rive-canvas are you using ? I saw they recently changed there API, but I didn't updated yet.
`ng-rive` should be working with rive-canvas@0.7.3

**Comment by n84ck** [comment]
I didn't install rive-canvas explicitly, I use your ng-rive plugin which already contains rive-canvas. (0.7.3). By the way the riv-animation works as expected.

**Comment by GrandSchtroumpf** [comment]
Hmmm ok might be because of the `^` in the package.json. In you package-lock.json the version or riev-canvas is 0.7.3 ?
I'll update to the latest version anyway asap but it might help me avoid future issues.

**Comment by n84ck** [comment]
The version is 0.7.5 in the package-lock.json. So this can be the reason. I will check after you update the library.
Thank you for the help.

**Comment by GrandSchtroumpf** [comment]
I updated the version to 0.7.6: https://github.com/dappsnation/ng-rive/pull/21
Please close the issue if it works.

**Comment by n84ck** [comment]
The issue is fixed. Thank you!
