### ISSUE TITLE
Does not work with strict Content Security Policy (CSP) that blocks unsafe-eval (new Function)

### ISSUE THREAD

**Issue by localpcguy** [dappsnation/ng-rive#24]
Pretty sure this is related to the Rive JS/WASM script, and I put an issue in on that repo here:
https://github.com/rive-app/rive-wasm/issues/131

But also wanted to add an issue to track it here both for others to find who may have a similar issue and so if it gets updated, the new version fixing it can be pulled in here.

**Comment by GrandSchtroumpf** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.

**Comment by localpcguy** [comment]
Sorry it took so long to get back to this - confirmed (per notes in the linked thread) that using `wasm-unsafe-eval` eliminates the need for the more generic `unsafe-eval` in the CSP.
