### ISSUE TITLE
Error with "OffscreenCanvas"

### ISSUE THREAD

**Issue by nivenf** [dappsnation/ng-rive#25]
Getting errors in canvas.d.ts and types.d.ts regarding OffscreenCanvas and OffscreenCanvasRenderingContext2D.

Console output:
Compiled with problems:X

ERROR

node_modules/ng-rive/lib/canvas.d.ts:18:33 - error TS2304: Cannot find name 'OffscreenCanvas'.

18     canvas: HTMLCanvasElement | OffscreenCanvas;
                                   ~~~~~~~~~~~~~~~


ERROR

node_modules/ng-rive/lib/canvas.d.ts:38:43 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

38     get ctx(): CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D;
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR

node_modules/ng-rive/lib/types.d.ts:52:49 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

52     constructor(ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D);
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


ERROR

node_modules/rive-canvas/types.d.ts:77:47 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

77   constructor(ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D);
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR

node_modules/rive-canvas/types.d.ts:81:40 - error TS2304: Cannot find name 'OffscreenCanvasRenderingContext2D'.

81   draw(ctx: CanvasRenderingContext2D | OffscreenCanvasRenderingContext2D, path: RenderPath): void;

**Comment by GrandSchtroumpf** [comment]
Hello, sorry for the delay. Looks like an error with the `lib` in tsconfig or something like that. 
`OffscreenCanvasRenderingContext2D` is a type from the web api so I suppose you need to have `"dom"` in the `"lib"` field of `tsconfig.json`. Like here for example : https://github.com/dappsnation/ng-rive/blob/master/tsconfig.base.json#L13.

Another solution would be to add `"skipLibCheck": true` into the `tsconfig.json` like here : https://github.com/dappsnation/ng-rive/blob/master/tsconfig.base.json#L14

I hope it helps.

**Comment by GrandSchtroumpf** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.
