### ISSUE TITLE
"Expected null or instance of LinearAnimation, got an instance of Animation" error when used inside a lazy-module.

### ISSUE THREAD

**Issue by SadraMoh** [dappsnation/ng-rive#26]
### Setup  
I have a generic angular applications with 3 modules - the app rootModule, a home featureModule and an about featureModule.
The Home and About featureModules are loaded lazily.
I have multiple animations playing in a page declared in the Home featureModule.
[localhost.log](https://github.com/dappsnation/ng-rive/files/8409878/localhost.log)

### Procedure  
1. Navigate to the about page which is declared in the lazy-loaded aboutFeatureModule.
2. Navigate back to the home page which is declared in the lazy-loaded homeFeatureModule.

## Expectation
The animations declared in the home page should be loaded and played as soon as the user navigates to the page.

## Observation / Issue
The animations are not loaded.
The following errors are printed to the console:
```
Uncaught BindingError {name: 'BindingError', message: 'Expected null or instance of LinearAnimation, got an instance of Animation', stack: 'BindingError: Expected null or instance of LinearA…) 
```
***the complete log file is viewable in the attached localhost.log**

## Notes
There are a total of 4 animations playing at the same time on four different canvases. occasionaly the last one loads perfectly without errors.

**Comment by localpcguy** [comment]
We are seeing the same thing with a new animation. Animations we've been running for months actually seem to be fine and don't ever seem to throw this error. I'm wondering if it's related to a new runtime maybe? I'll report back if outputting the animations via the previous runtime makes a difference.

**Comment by GrandSchtroumpf** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.
