### ISSUE TITLE
Update to use newer Rive app npm package? @rive-app/canvas is recommended

### ISSUE THREAD

**Issue by localpcguy** [dappsnation/ng-rive#31]
Looks like Rive has been fairly busy and updated the WASM runtimes significantly, and now have new npm packages they recommend instead of the rive-js / rive-canvas they previously used (and that this uses currently). Are there plans for this plugin to update to use the newer packages?

The [migration guide](https://help.rive.app/runtimes/overview/web-js/migrating-from-rive-js) indicates it should be compatible with the same API. The [runtime docs](https://github.com/rive-app/rive-wasm/blob/master/WEB_RUNTIMES.md) recommend the @rive-app/canvas barring any specific needs, but I haven't looked into the specifics of whether that would just work with the existing Angular wrapper components here or if other updates would be needed, so I don't have a good sense of how big a task this is.

Could potentially allow closing #24 as their upstream recommendation is to use the newer runtime. And similarly for a [JS error when WebAssembly isn't available](https://github.com/rive-app/rive-wasm/issues/147) I reported on their repo.

**Comment by GrandSchtroumpf** [comment]
Hello, thanks for the comment. I'm sorry for the delay, I've been quite busy recently and didn't updated this lib for a while.
I'll take some time in the upcoming days to update all of it.

**Comment by GrandSchtroumpf** [comment]
Quick update, ng-rive wasn't using rive-js but the old rive-canvas with the low-level access to the Wasm API. It allows some angular optimization that wasn't possible with rive-js 
I'll need to update with @rive/canvas-advance and @rive/webgl-advance, so it might take some time, and introduce breaking changes.

**Comment by GrandSchtroumpf** [comment]
@localpcguy did you have the time to try it ? Can I close this issue ?

**Comment by localpcguy** [comment]
Yes, sorry - we recently prioritized updating some of our very old Rive files which allowed us to update this package as well and it is working great. Thanks for your work on this!
