### ISSUE TITLE
Listeners not working?

### ISSUE THREAD

**Issue by magwo** [dappsnation/ng-rive#40]
Thanks for an interesting library!

We have an Angular 15 app (using OnPush change detection if it matters).
When we try using Rive animations none of the Listeners specified by the designer appear to have any effect.

For example, onmousemove or onpointerdown don't appear to have any effect and the animation is completely non-interactive in Angular, despite being interactive in the play/demo mode.

Is this to be expected or are we doing something incorrectly in our Angular code?

Best regards!
/Magnus

**Comment by GrandSchtroumpf** [comment]
Hello, I'm sorry for that issue. Could you share you animation so I can try it ?
As a side note I've worked a lot with Rive lately, I can be a little long to response. Don't hesitate to tag me.

**Comment by magwo** [comment]
Well, to take a step back. Are pointer/mouse listeners supposed to work out of the box in ng-rive? Like they do in the Rive community examples? Without any coding?

For us, basic animations work fine but none of the Listener functionality appears to work. Nothing happens upon mouse interactions like in the example [here](https://rive.app/community/).

We tried downloading and using several of those interactive animations in our project. None of them were interactive in our Angular app, and it could very well be that we're doing something weird with events, for example with pointer-events styling etc.

I just want to get a clear picture of the scope of ng-rive before going deeper. Is Rive interactivity supposed to work without any added code?

**Comment by magwo** [comment]
Here's an interactive Rive animation that was not interactive in our Angular app:

[coffee_cup.riv.zip](https://github.com/dappsnation/ng-rive/files/11309603/coffee_cup.riv.zip)

**Comment by GrandSchtroumpf** [comment]
@magwo Thanks for pointing that out, I actually missed this feature.
After digging a little bit into the rive-wasm repo I found out the [code responsible for that](https://github.com/rive-app/rive-wasm/blob/master/js/src/utils/registerTouchInteractions.ts).
I'll do my best to integrate it asap.

**Comment by magwo** [comment]
Aha! Nice, thanks! Looking forward to it!

**Comment by magwo** [comment]
Very cool! Thanks!
