### ISSUE TITLE
v 0.2.6 LinearAnimationInstance instance already deleted 

### ISSUE THREAD

**Issue by phpgeekfr** [dappsnation/ng-rive#46]
We use  `<riv-animation>` tag  to display a custom loader instead of `<mat-spinner>` from materials. 
When page is loaded, `<riv-animation>` is not displayed anymore and we have a message `LinearAnimationInstance instance already deleted `.

This was not the case with  `0.2.3`

**Comment by GrandSchtroumpf** [comment]
Version 0.2.6 introduced a fix version of the wasm by default.
Ideally the version of the wasm file & the version of `@rive-app/canvas-advanced` should match. I've not created a table of matching version between `ng-rive` & `@rive-app/canvas-advanced` yet, but there is a dedicated branch for each version, so you can easily check the `package.json` file on the branch you are interested in to get the correct version.

I'll close the issue for book keeping, but don't hesitate to reopen if it doesn't fix it.
