### ISSUE TITLE
2-way bindings deprecated ?

### ISSUE THREAD

**Issue by wibimaster** [dappsnation/ng-rive#51]
When we use the `<riv-player>`, the documentation states that we can use the `[(play)]` binding.
But, in the code, it seems to be deprecated :
https://github.com/dappsnation/ng-rive/blob/86de1fd306a73733fa994b3e42a02cf91a93824e/libs/ng-rive/src/lib/player.ts#L160-L161

How can we know if the animation is playing / is finished, without using this ?
Is there any other event we can use ?

Thanks !

**Comment by wibimaster** [comment]
I found a way using

`<riv-player #player="rivPlayer" name="animation_name" [play]="isPlaying"></riv-player>`

```
ngAfterViewInit() {
    this.player.state.subscribe((data: any) => {
      console.log(data);
    });
}
```

But I'm not comfortable with mixing events and attributes...

**EDIT** It doesn't work, when the animation is finished, the "state" event isn't triggered and we don't know if "play" is false

**Comment by GrandSchtroumpf** [comment]
I think this was a mistake to deprecate it. I'll remove it in 3.0.1
Basically the player is doing much more work than the LinearAnimation to keep track of position, and I thought best would be to move everything to the `riv-animation`. But after reading you I see there is still use cases for the `riv-player`.
Keep in mind that `riv-player` will do more calculation than `riv-animation`, but for your use case I guess you need it.
